version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the prebuild phase"
  build:
    commands:
      - echo "Entered the build phase"
      - mvn clean prepare-package war:exploded
  post_build:
    commands:
      - echo "Entered the postbuild phase"
artifacts:
  files:
    - target/01-spring-boot-hello-world-rest-api-0.0.1-SNAPSHOT.jar
